//------------------------------------------------------------------------------
// <auto-generated>
//     This file is auto-generated by the ASP.NET designer.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LdapAuthApp
{
    public partial class DashboardPage
    {
        protected global::System.Web.UI.WebControls.Label          lblDisplayName;
        protected global::System.Web.UI.WebControls.Label          lblInitials;
        protected global::System.Web.UI.WebControls.Label          lblFullName;
        protected global::System.Web.UI.WebControls.Label          lblTitle;
        protected global::System.Web.UI.WebControls.Label          lblSam;
        protected global::System.Web.UI.WebControls.Label          lblEmail;
        protected global::System.Web.UI.WebControls.Label          lblDept;
        protected global::System.Web.UI.WebControls.Label          lblPhone;
        protected global::System.Web.UI.WebControls.Label          lblDN;
        protected global::System.Web.UI.WebControls.Panel          pnlGroups;
        protected global::System.Web.UI.WebControls.Panel          pnlNoGroups;
        protected global::System.Web.UI.WebControls.Repeater       rptGroups;
        protected global::System.Web.UI.WebControls.Button         btnLogout;
    }
}
