//------------------------------------------------------------------------------
// <auto-generated>
//     This file is auto-generated by the ASP.NET designer.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LdapAuthApp
{
    public partial class LoginPage
    {
        protected global::System.Web.UI.WebControls.Panel   pnlError;
        protected global::System.Web.UI.WebControls.Label   lblError;
        protected global::System.Web.UI.WebControls.TextBox txtUsername;
        protected global::System.Web.UI.WebControls.TextBox txtPassword;
        protected global::System.Web.UI.WebControls.Button  btnLogin;
    }
}
