//------------------------------------------------------------------------------
// <auto-generated>
//     This file is auto-generated by the ASP.NET designer.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LdapAuthApp
{
    public partial class SearchPage
    {
        protected global::System.Web.UI.WebControls.DropDownList ddlType;
        protected global::System.Web.UI.WebControls.TextBox      txtQuery;
        protected global::System.Web.UI.WebControls.TextBox      txtBaseDn;
        protected global::System.Web.UI.WebControls.TextBox      txtMax;
        protected global::System.Web.UI.WebControls.Button       btnSearch;
        protected global::System.Web.UI.WebControls.Panel        pnlFilterPreview;
        protected global::System.Web.UI.WebControls.Label        lblFilter;
        protected global::System.Web.UI.WebControls.Panel        pnlStatus;
        protected global::System.Web.UI.WebControls.Literal      litStatus;
        protected global::System.Web.UI.WebControls.Panel        pnlResults;
        protected global::System.Web.UI.WebControls.Label        lblCount;
        protected global::System.Web.UI.WebControls.Repeater     rptResults;
        protected global::System.Web.UI.WebControls.Button       btnLogout;
    }
}
